mode: inorder #inorder, random
poses:
  - pose:
      position:
        x: 6.0
        y: -2.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
  - pose:  
      position:
        x: -2.0
        y: 4.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
  - pose: 
      position:
        x: 0.0
        y: -2.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
  # - pose:  
  #     position:
  #       x: -2.0
  #       y: 1.0
  #       z: 0.0
  #     orientation:
  #       x: 0.0
  #       y: 0.0
  #       z: 0.0
  #       w: 0.0