/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: false
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: true
    planner_frequency: 0.2
    progress_timeout: 200.0
    potential_scale: 0.001
    orientation_scale: 0.0
    gain_scale: 1.0
    transform_tolerance: 0.1
    min_frontier_size: 0.3